POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer $2b$10$hDVWX8Pk7PxC3L/YXIXNwOIM2TbK3HPQx49AeWN4T4eYUHDULgQYa 

{
    "title": "Blog Auth",
    "author": "Idk lol",
    "url": "prova.net",
    "likes": 99
}