POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer $2b$10$8s6qhRybTq3rK0IqfuA4m.IgLzYtenH3iolG//RByKBD6v4OengwO 

{
    "title": "Blog Auth",
    "author": "Idk lol",
    "url": "prova.net",
    "likes": 99
}