POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik51b3ZvU2VjcmV0IiwiaWQiOiI2MTY5ODRiYjlkYTQyNzNlYTE2YWI1ZTkiLCJpYXQiOjE2MzQzMTE5NDksImV4cCI6MTYzNDMxNTU0OX0.RkcBWTU1_cyEM5Vof5cBAUpnNUCS6K9yS0UjHEvvTzE

{
    "title": "Blog Auth",
    "author": "Idk lol",
    "url": "prova.net",
    "likes": 0,
}